config/routes.rb
Rails.application.routes.draw do
  root to: 'users#home'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  resources :sessions, only: [:create]
  resources :comments, only: [:new, :create, :show, :destroy]
  resources :users
  post 'foods/:id/likes/:id', to: 'likes#create_food_like', as: 'like_food'
  post 'drinks/:id/likes/:id', to: 'likes#create_drink_like', as: 'like_drink'
  get 'random_food', to: 'foods#random', as: 'random_food'
  get 'random_drink', to: 'drinks#random', as: 'random_drink'
  resources :foods do 
    resources :likes 
  end 
  resources :drinks do 
    resources :likes 
  end 
  
end

app/models/drink.rb
class Drink < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :recipe
  has_many :likes, as: :post

  validates_presence_of :category, :name, :ingredients, :directions, :image_url

  def self.most_liked
    Drink.all.max_by{|drink| drink.likes.count}
  end

  def self.random
    Drink.all.sample 
  end

  def self.most_comments
    Drink.all.max_by{|drink| drink.comments.count}
  end

  def city
    self.user.city
  end

  def self.top_five_likes
    Drink.all.sort{|drink| drink.likes.count}.last(5).reverse
  end
  
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
    def new
        @drink = Drink.new
    end

    def update
        @drink= Drink.find(params[:id])
        @drink.update(drink_params)
	    if @drink.valid?
            redirect_to @drink
	    else
	    	flash[:errors] = @drink.errors.full_messages
	    	redirect_to edit_drink_path
	    end
    end

    def create
        @drink = Drink.create(drink_params)
        if @drink.valid? 
		    redirect_to @drink
	    else 
		    flash[:errors] = @drink.errors.full_messages
		    redirect_to new_drink_path
	    end
    end

    def edit
        @drink = Drink.find(params[:id])
    end

    def show
        @drink = Drink.find(params[:id])
        @comment = Comment.new
        @comments = Comment.where(recipe_id: @drink.id, recipe_type: @drink.class.to_s)
    end
	
    def index
	    @drinks = Drink.all
    end

    def destroy 
	    @drink = Drink.find(params[:id])
	    @drink.destroy
	    redirect_to drinks_path
    end 

    def random 
        redirect_to Drink.random
    end 

    private
    def drink_params
        params.require(:drink).permit(:name, :category, :ingredients, :directions, :image_url, :user_id)
    end
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/views/drinks/edit.html.erb
<% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
      <p><%= error %></p>
    <% end %>
<% end %>
<% if @drink.user == current_user %>
<h2>Edit Drink Recipe</h2>
<%= form_with model:@drink do |f|%>
    <%= f.label :name %>
    <%= f.text_field :name %> <br><br>

    <%= f.label :category %>
    <%= f.text_field :category %><br><br>

    <%= f.label :ingredients %>
    <%= f.text_area :ingredients %><br><br>

    <%= f.label :directions %>
    <%= f.text_area :directions %><br><br>

    <%= f.label :image_url %>
    <%= f.text_field :image_url %><br><br>
    
    <%= f.submit %>
<% end %>
<% else %>
<h1 style="color:red"><b>Acceess Denied</b></h1>
<% end %>

app/views/drinks/index.html.erb
<h2>Drink Recipes</h2><br>
<% @drinks.each do |drink|%>
<h5>
    <%= link_to drink.name, drink %> <br>
    Created by: <%= link_to drink.user.name, drink.user %> <br>
    Category: <%= drink.category %></h5><br>
    <%= image_tag drink.image_url, size: "200x225"%> <br><br>
<% end %>

app/views/drinks/new.html.erb
<% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
      <p><%= error %></p>
    <% end %>
<% end %>
<h2>New Drink Recipe</h2>
<%= form_with model:@drink do |f|%>
    <%= f.label :name %> <br>
    <%= f.text_field :name %> <br><br>

    <%= f.label :category %> <br>
    <%= f.text_field :category %><br><br>

    <%= f.label :ingredients %> <br>
    <%= f.text_area :ingredients %><br><br>

    <%= f.label :directions %> <br>
    <%= f.text_area :directions %><br><br>

    <%= f.label :image_url %> <br>
    <%= f.text_field :image_url %><br><br>
    
    <%= f.hidden_field :user_id, value: session[:user_id] %>
    <%= f.submit %>
<% end %>

app/views/drinks/show.html.erb
<h2><%= @drink.name %> </h2>
<h5>
Created by: <%=link_to @drink.user.name, @drink.user%> <br><br>
<b>Ingredients:</b> <%= @drink.ingredients %> <br><br>
<b>Directions: </b><%= @drink.directions %> </h5><br><br>
<%= image_tag @drink.image_url, size:"500x600"%> <br><br>

<p><%= @drink.likes.count %> <%= (@drink.likes.count) == 1 ? 'Like' : 'Likes'%></p><br>

<% if flash[:notice] %> 
    <%= flash[:notice] %><br>
<% end %>

<% if current_user %>
<%= button_to 'Like', drink_like_path(@drink), method: :post %> <br>
<% end %>

<% if current_user == @drink.user %>
    <%= button_to "Edit", edit_drink_path, method: :get %> <br><br>
<% end %>

<h3>Comment Section</h3>

<% @comments.each do |comment|%>
    <%= link_to comment.user.name, comment.user %> : <br>
    <%= comment.content %> 
    <% if current_user == comment.user %>
        <%= button_to "delete comment", comment_path(comment), method: :delete %>
    <% end %>
    <br> <br>
<% end %>

<% if current_user %>
<%= form_with model:@comment do |f|%>
    <%= f.label "Add Comment" %>: <br>
    <%= f.text_area :content %> <br>
    <%= f.hidden_field :recipe_id, value: @drink.id %>
    <%= f.hidden_field :recipe_type, value: @drink.class %>
    <%= f.hidden_field :user_id, value: session[:user_id] %>
    <%= f.submit %>
<% end %>
<% end %>