config/routes.rb
Rails.application.routes.draw do
  root to: 'users#home'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  resources :sessions, only: [:create]
  resources :comments, only: [:new, :create, :show, :destroy]
  resources :users
  post 'foods/:id/likes/:id', to: 'likes#create_food_like', as: 'like_food'
  post 'drinks/:id/likes/:id', to: 'likes#create_drink_like', as: 'like_drink'
  get 'random_food', to: 'foods#random', as: 'random_food'
  get 'random_drink', to: 'drinks#random', as: 'random_drink'
  resources :foods do 
    resources :likes 
  end 
  resources :drinks do 
    resources :likes 
  end 
  
end

app/models/user.rb
class User < ApplicationRecord
    has_many :foods, dependent: :destroy
    has_many :drinks, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_secure_password
    validates_presence_of :name, :city, :username 
    validates_uniqueness_of :username


    def self.most_pop_city
        cities = User.all.map{|user| user.city}
        city = cities.max_by{|town| cities.count(town)}
    end 

    def self.most_food_posts
        User.all.max_by{|user| user.foods.count} 
    end 

    def self.most_drink_posts
        User.all.max_by{|user| user.drinks.count}
    end 

    def featured_food 
        self.foods.max_by{|user| user.likes.count}
    end 
    
    def featured_drink 
        self.drinks.max_by{|user| user.likes.count}
    end 

    def all_likes 
        food_likes = self.foods.sum{|user| user.likes.count}
        drink_likes = self.drinks.sum{|user| user.likes.count}
        total = food_likes + drink_likes
    end 

    def all_posts 
        total_post = self.foods.count + self.drinks.count
        
    end

    def self.like_sort 
        User.all.sort_by{|user| user.all_likes}.reverse
    end

    def self.top_three_active 
        User.all.sort_by{|user| user.comments.count}.last(3).reverse
    end 
    

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index 
        @users = User.all
    end 

    def show 
        @user = User.find(params[:id])
    end 

    def home 
    end 

    def new 
        @user = User.new 
    end 

    def create 
        @user = User.create(user_params)
        if @user.valid?
            redirect_to @user
        else 
            flash[:errors] = @user.errors.full_messages
            redirect_to new_user_path
        end
    end 

    def edit 
        @user = User.find(params[:id]) 
    end 

    def update 
        @user = User.find(params[:id])
        @user.update(user_params)
        if @user.valid?
            redirect_to @user
        else 
            flash[:errors] = @user.errors.full_messages
            redirect_to new_user_path
        end
    end 

    def destroy 
        @user = User.find(params[:id])
        @user.destroy
    end 

    private 

    def user_params 
        params.require(:user).permit(:name, :city, :password, :username)
    end 

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.erb
<% if flash[:errors] %> 
    <% flash[:errors].each do |error| %> 
    <%= error %> 
    <% end %> 
<% end %>

<%= form_with model:@user do |f| %> 

    <%= f.label :name %> <br>
    <%= f.text_field :name %><br><br>

    <%= f.label :city %> <br>
    <%= f.text_field :city %><br><br>

    <%= f.label :password %> <br>
    <%= f.password_field :password %><br><br>

    <%= f.label :username %> <br>
    <%= f.text_field :username %><br><br>

    <%= f.submit %>
    <% end %> 

app/views/users/edit.erb
<h2>User Edit Form</h2> 

<%= render 'form' %>

app/views/users/home.erb
<main class="container">

      <h1 class="display-4 font-italic">Welcome to Food and Drink</h1>
      <p class="lead my-3">A place for creative chefs to showcase their recipes.</p>

  <div class="row mb-2" style="height:450px; overflow:auto">
    <div class="col-md-6">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <h3 class="mb-0">Featured Food Recipe</h3>
           <%= link_to Food.most_liked.name + " by " + Food.most_liked.user.name, Food.most_liked %><br><br>
        </div>
        <div class="col-auto d-none d-lg-block">
        <%= image_tag Food.most_liked.image_url, size: "300x325"%>
        </div>
      </div>
    </div>

    <div class="col-md-6">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <h3 class="mb-0">Featured Drink Recipe</h3>
           <%= link_to Drink.most_liked.name + " by " + Drink.most_liked.user.name, Drink.most_liked %><br><br>
        </div>
        <div class="col-auto d-none d-lg-block">
        <%= image_tag Drink.most_liked.image_url, size: "300x325"%>
        </div>
      </div>
    </div>
  </div>

  <hr>

  <div class="col-md-6 px-0">
    <h2>Easiest and Lowest Prep Meal</h2>
    <p class="lead my-3">Meals that are as fewest ingredients yet taste great!</p>
    <p class="lead mb-0"><%= link_to "Continue to recipe...", Food.least_ingredients %></p>
    
    <h2>Low And Slow Meal</h2>
    <p class="lead my-3">Meals That Have A Long Cook Time</p>
    <p class="lead mb-0"><%= link_to "Continue to recipe...", Food.longest_time %></p>

        <hr>
      <div class="p-4 mb-3 bg-light rounded">
        <h3 class="font-italic">Most Popular City For Chefs</h3>
        <p class="mb-0"><h4><%= User.most_pop_city %><h4></p>
      </div>

      <div class="p-4">
            <h3 class="font-italic">Top 5 Food Recipes</h3>
            <ol class="list-unstyled mb-0">
                <% Food.top_five_foods.each do |food| %> 
                    <li><h4><%= link_to food.name, food %></h4></li>
                <% end %>
            </ol>
      </div>

      <div class="p-4">
            <h3 class="font-italic">Top 5 Drink Recipes</h3>
            <ol class="list-unstyled">
                <% Drink.top_five_likes.each do |drink| %> 
                     <li><h4><%= link_to drink.name, drink %></h4></li>
                <% end %> 
            </ol>
      </div>
    <hr>
      <div class="p-4">
            <h3 class="font-italic">Meals Under 30 Minutes</h3>
            <ol class="list-unstyled">
                 <% Food.shortest_time.each do |time| %> 
                    <li><h4><%= link_to time.name, time %></h4></li> 
                <% end %> 
            </ol>
        </div>
    </div>


  <div class="row">
    <div class="col-md-6">
      <article class="blog-post">
        <h2>Whats Hot Right Now!</h2>
        
        <h4><%= link_to Food.most_comments.name + " by " + Food.most_comments.user.name, Food.most_comments %><br></h4>
        <p class="blog-post-meta">Created: <%= Food.most_comments.created_at.strftime("%B %d, %Y") %></p>
        <p>"<%= Food.most_comments.comments.last.content %>" - <%= Food.most_comments.comments.last.user.name %></p>
        <%= image_tag Food.most_comments.image_url, size: "250x275"%><br><br>

        <hr>
        
        <h4><%= link_to Drink.most_comments.name + " by " + Drink.most_comments.user.name, Drink.most_comments %><br></h4>
        <p class="blog-post-meta">Created: <%= Drink.most_comments.created_at.strftime("%B %d, %Y") %></p>
        <p>"<%= Drink.most_comments.comments.last.content %>" - <%= Drink.most_comments.comments.last.user.name %></p>
        <%= image_tag Drink.most_comments.image_url, size: "250x275"%><br><br>

        <hr>

        <div> 
            <h3 class="font-italic">Unsure Of What To Make?</h3>
            Food: <%= button_to "I'm Feeling Hungry", random_food_path, method: :get %><br> 

            Drink: <%= button_to "I'm Feeling Thirsty", random_drink_path, method: :get %>

        </div> 
        <div class="p-4">
            <h3 class="font-italic">Most Active Chefs</h3>
            <ol class="list-unstyled">
                <li><h4><%= link_to User.most_food_posts.name, User.most_food_posts %> - <%= User.most_food_posts.foods.count.to_s + " posts" %></h4></li>
                <li><h4><%= link_to User.most_drink_posts.name, User.most_drink_posts %> - <%= User.most_drink_posts.drinks.count.to_s + " posts"%></h4></li>
            </ol>
        </div>             


    </div>

  </div><!-- /.row -->

</main>

app/views/users/index.erb
<div class="p-4">
      <h3 class="font-italic">Top 3 Active Chefs</h3>
      <ol class="list-unstyled">
         <% User.top_three_active.each do |user| %> 
            <li><h4><%= link_to user.name, user %></h4></li>
            <% end %> 
            </ol>
<hr>
      <h3 class="font-italic">All Chefs</h3>
      <ol class="list-unstyled">
         <% User.like_sort.each do |user| %> 
            <li><h4><%= link_to user.name + " from " + user.city + " with " + user.all_posts.to_s + " posts. ", user %></h4></li>
            <% end %> 
            </ol>
</div> 

app/views/users/new.erb
<h2>New Account Signup</h2>

<%= render 'form' %>

app/views/users/show.erb
<h2><%= @user.name %></h2><br>
Username: <%= @user.username %><br><br>
City: <%= @user.city %><br><br>

<% if current_user == @user %>
<%= button_to "Sign Out", logout_path, method: :get %> <br>
<% end %>
<hr>

<div class="position-relative row mb-2" style="height:450px; overflow:auto">
    <div class="col-md-6">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <h3 class="mb-0">Featured Food Recipe</h3>
          <% if @user.featured_food%>
           <%= link_to @user.featured_food.name + " by " + @user.featured_food.user.name, @user.featured_food %><% end %><br><br>
        </div>
        <div class="col-auto d-none d-lg-block">
        <% if @user.featured_food%>
        <%= image_tag @user.featured_food.image_url, size: "300x325"%>
        <% end %>
        </div>
      </div>
    </div>


    <div class="col-md-6">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <h3 class="mb-0">Featured Drink Recipe</h3>
          <% if @user.featured_drink %>
           <%= link_to @user.featured_drink.name + " by " + @user.featured_drink.user.name, @user.featured_drink %><% end %>
           <br><br>
        </div>
        <div class="col-auto d-none d-lg-block">
        <% if @user.featured_drink %>
        <%= image_tag @user.featured_drink.image_url, size: "300x325"%><% end %>
        </div>
      </div>
    </div>
  </div>

<hr>


<div class="position-relative">
    <h4>All Food Recipes:</h4>
    <% if current_user == @user %>
    <%= button_to "Create New Recipe", new_food_path, method: :get %> <br>
    <% end %>

    <% @user.foods.each do |f| %> 
    <b>- </b> <%= link_to f.name, food_path(f) %><br>
    <% end %>


    <h4>All Drink Recipes:</h4>
    <% if current_user == @user %>
    <%= button_to "Create New Recipe", new_drink_path, method: :get %> <br>
    <% end %>

    <% @user.drinks.each do |d| %>
    <b>- </b> <%= link_to d.name, drink_path(d) %><br>
    <% end %> 

    <h4>All likes</h4> 
    <%= @user.all_likes %>
</div>