config/routes.rb
Rails.application.routes.draw do
  root to: 'users#home'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  resources :sessions, only: [:create]
  resources :comments, only: [:new, :create, :show, :destroy]
  resources :users
  post 'foods/:id/likes/:id', to: 'likes#create_food_like', as: 'like_food'
  post 'drinks/:id/likes/:id', to: 'likes#create_drink_like', as: 'like_drink'
  get 'random_food', to: 'foods#random', as: 'random_food'
  get 'random_drink', to: 'drinks#random', as: 'random_drink'
  resources :foods do 
    resources :likes 
  end 
  resources :drinks do 
    resources :likes 
  end 
  
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :recipe
  has_many :likes, as: :post

  validates_presence_of :category, :name, :ingredients, :directions, :image_url, :time 

  def self.most_liked
    Food.all.max_by{|food| food.likes.count}
  end

  def self.random
    Food.all.sample
  end

  def self.most_comments
    Food.all.max_by{|food| food.comments.count}
  end

  def self.longest_time
    Food.find_by(time: Food.maximum(:time))
  end

  def self.shortest_time
    Food.where("time < 31").limit(10)
  end

  def self.top_five_foods
    Food.all.sort{|food| food.likes.count}.last(5).reverse
  end

  def self.least_ingredients
    Food.all.min_by{|food| food.ingredients.split(",")}
  end

end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
    
    def index 
        @foods = Food.all 
    end 

    def show 
        @food = Food.find(params[:id])
        @comment = Comment.new 
        @comments = Comment.where(recipe_id: @food.id, recipe_type: @food.class.to_s)
    end 

    def new 
        @food = Food.new 
    end 

    def create 
        
        @food = Food.create(food_params)
        if @food.valid?
            redirect_to @food 
        else 
            flash[:errors] = @food.errors.full_messages
            redirect_to new_food_path
        end

    end 

    def edit 
        @food = Food.find(params[:id])
    end 

    def update 
        @food = Food.find(params[:id])
        @food.update(food_params)
        if @food.valid?
            redirect_to @food 
        else 
            flash[:errors] = @food.errors.full_messages
            redirect_to edit_food_path
        end 
    end 

    def destroy 
        @food = Food.find(params[:id])
        @food.destroy
        redirect_to foods_path
    end 

    def random 
        redirect_to Food.random
    end 

    private 

    def food_params 
        params.require(:food).permit(:category, :name, :ingredients, :directions, :image_url, :time, :user_id)
    end 

end 

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_form.erb
<% if flash[:errors] %> 
    <% flash[:errors].each do |error| %> 
    <%= error %> 
    <% end %> 
<% end %>

<%= form_with model:@food do |f| %> 

    <%= f.label :name %> <br>
    <%= f.text_field :name %><br><br>

    <%= f.label :category %> <br>
    <%= f.text_field :category %><br><br>

    <%= f.label :ingredients %> <br>
    <%= f.text_area :ingredients %><br><br>

    <%= f.label :directions %> <br>
    <%= f.text_area :directions %><br><br>

    <%= f.label :image_url %> <br>
    <%= f.text_field :image_url %><br><br>

    <%= f.label "Time (minutes)" %> <br>
    <%= f.number_field :time %><br><br>
    
    <%= f.hidden_field :user_id, value: session[:user_id] %>
    <%= f.submit %>
    <% end %> 

app/views/foods/edit.erb
<% if @food.user == current_user %>
<h1>Edit Food Form</h1>

<%= render 'form' %>
<% else %>
<h1 style="color:red"><b>Acceess Denied</b></h1>
<% end %>

app/views/foods/index.erb
<h2>Food Recipes</h2> <br>
<% @foods.each do |food|%>
    <h5>
    <%= link_to food.name, food %> <br>
    Created by: <%= link_to food.user.name, food.user %> <br>
    Category: <%= food.category %><br><br></h5>
    <%= image_tag food.image_url, size: "200x225"%> <br><br>
<% end %>

app/views/foods/new.erb
<h2>New Food Form</h2> 

<%= render 'form' %> 

app/views/foods/show.erb
<h2><%= @food.name %> </h2>
<h5>
Created by: <%= link_to @food.user.name, @food.user %> <br>
Time: <%= @food.time.to_s + " minutes" %> <br><br>
<b>Ingredients:</b> <%= @food.ingredients %> <br><br>
<b> Directions:</b> <%= @food.directions %> </h5><br><br>
<%= image_tag @food.image_url, size:"500x600"%> <br><br>

<p><%= @food.likes.count %> <%= (@food.likes.count) == 1 ? 'Like' : 'Likes'%></p><br>

<% if flash[:notice] %> 
    <%= flash[:notice] %><br>
<% end %>

<% if current_user %>
<%= button_to 'Like', food_like_path(@food), method: :post %>
<% end %>

<% if current_user == @food.user %>
    <%= button_to "Edit", edit_food_path, method: :get %> <br><br>
<% end %>

<h3>Comment Section</h3>

<% @comments.each do |comment|%>
    <%= link_to comment.user.name, comment.user %> : <br>
    <%= comment.content %> 
    <% if current_user == comment.user %>
        <%= button_to "delete comment", comment_path(comment), method: :delete %>
    <% end %>
    <br> <br>
<% end %>

<% if current_user %>
<%= form_with model:@comment do |f|%>
    <%= f.label "Add Comment" %>: <br>
    <%= f.text_area :content %> <br>
    <%= f.hidden_field :recipe_id, value: @food.id %>
    <%= f.hidden_field :recipe_type, value: @food.class %>
    <%= f.hidden_field :user_id, value: session[:user_id] %>
    <%= f.submit %>
<% end %>
<% end %>