config/routes.rb
Rails.application.routes.draw do
  root to: 'users#home'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  resources :sessions, only: [:create]
  resources :comments, only: [:new, :create, :show, :destroy]
  resources :users
  post 'foods/:id/likes/:id', to: 'likes#create_food_like', as: 'like_food'
  post 'drinks/:id/likes/:id', to: 'likes#create_drink_like', as: 'like_drink'
  get 'random_food', to: 'foods#random', as: 'random_food'
  get 'random_drink', to: 'drinks#random', as: 'random_drink'
  resources :foods do 
    resources :likes 
  end 
  resources :drinks do 
    resources :likes 
  end 
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Food & Drink</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" %>
    <link href="https://getbootstrap.com/docs/4.0/examples/pricing/pricing.css" rel="stylesheet">
    <%=stylesheet_link_tag "https://getbootstrap.com/docs/4.0/examples/blog/blog.css"%>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="margin:auto;width:80%;">
    <header class="blog-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
          <div class="col-4 text-center">
            <h1 style="font-family:cursive; font-size:5vw;"class="blog-header-logo text-dark"><%= link_to "Food & Drink", root_path, style:"color:#000" %></h1><br>
          </div>
          
        </div>
      </header>
    <nav class="navbar navbar-expand border-bottom navbar-inverse" style="background-color:#fffff9; border-color:#FFF;">
      <div style="margin: 5px 20px">
        <div class="navbar-header">
        <%= link_to "Home", root_path, style:"color:#000;", class: "navbar-brand" %>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Drink Recipes", drinks_path, style:"color:#000" %></li>
          </ul>
          <ul class="nav navbar-nav">
            <li><%= link_to "Food Recipes", foods_path, style:"color:#000" %></li>
          </ul>
          <ul class="nav navbar-nav">
            <li><%= link_to "All Chefs", users_path, style:"color:#000" %></li>
          </ul>
          <% if current_user %>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Profile", current_user, style:"color:#000; margin-right:20px" %></li>
            </ul>
          <% else %>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Log In", login_path, style:"color:#000; margin-right:20px" %></li>
            </ul>
          <% end %>
        </div>
      </div>
    </nav>
    <div style="text-align:center;"><%= yield %></div>
  </body>
</html>